require:
  - rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
 Max: 20

AllCops:
 TargetRubyVersion: 2.7.0
 NewCops: enable
 Exclude:
    - db/schema.rb
    - db/migrate/*
    - bin/*
    - config/**/*
    - Gemfile